language: python
services:
  - postgresql
python:
  - "3.6"
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/db
install:
  - pip install -r requirements-local.txt coveralls
script:
  - tox
  - coverage run --source=work-at-olist/channels work-at-olist/manage.py test channels
after_success:
  - coveralls
