# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='reference',
            field=models.SlugField(max_length=100, verbose_name='Reference'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('channel', 'name', 'parent')]),
        ),
    ]
