# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20170719_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='reference',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Reference'),
        ),
    ]
